/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddBookOptions {
    #[serde(rename = "addType", skip_serializing_if = "Option::is_none")]
    pub add_type: Option<models::BookAddType>,
    #[serde(rename = "searchForNewBook", skip_serializing_if = "Option::is_none")]
    pub search_for_new_book: Option<bool>,
}

impl AddBookOptions {
    pub fn new() -> AddBookOptions {
        AddBookOptions {
            add_type: None,
            search_for_new_book: None,
        }
    }
}

