/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AllowFingerprinting {
    #[serde(rename = "never")]
    Never,
    #[serde(rename = "newFiles")]
    NewFiles,
    #[serde(rename = "allFiles")]
    AllFiles,

}

impl std::fmt::Display for AllowFingerprinting {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Never => write!(f, "never"),
            Self::NewFiles => write!(f, "newFiles"),
            Self::AllFiles => write!(f, "allFiles"),
        }
    }
}

impl Default for AllowFingerprinting {
    fn default() -> AllowFingerprinting {
        Self::Never
    }
}

