/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthorEditorResource {
    #[serde(rename = "authorIds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub author_ids: Option<Option<Vec<i32>>>,
    #[serde(rename = "monitored", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub monitored: Option<Option<bool>>,
    #[serde(rename = "monitorNewItems", skip_serializing_if = "Option::is_none")]
    pub monitor_new_items: Option<models::NewItemMonitorTypes>,
    #[serde(rename = "qualityProfileId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub quality_profile_id: Option<Option<i32>>,
    #[serde(rename = "metadataProfileId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata_profile_id: Option<Option<i32>>,
    #[serde(rename = "rootFolderPath", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub root_folder_path: Option<Option<String>>,
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<Vec<i32>>>,
    #[serde(rename = "applyTags", skip_serializing_if = "Option::is_none")]
    pub apply_tags: Option<models::ApplyTags>,
    #[serde(rename = "moveFiles", skip_serializing_if = "Option::is_none")]
    pub move_files: Option<bool>,
    #[serde(rename = "deleteFiles", skip_serializing_if = "Option::is_none")]
    pub delete_files: Option<bool>,
}

impl AuthorEditorResource {
    pub fn new() -> AuthorEditorResource {
        AuthorEditorResource {
            author_ids: None,
            monitored: None,
            monitor_new_items: None,
            quality_profile_id: None,
            metadata_profile_id: None,
            root_folder_path: None,
            tags: None,
            apply_tags: None,
            move_files: None,
            delete_files: None,
        }
    }
}

