/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AuthorStatusType {
    #[serde(rename = "continuing")]
    Continuing,
    #[serde(rename = "ended")]
    Ended,

}

impl std::fmt::Display for AuthorStatusType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Continuing => write!(f, "continuing"),
            Self::Ended => write!(f, "ended"),
        }
    }
}

impl Default for AuthorStatusType {
    fn default() -> AuthorStatusType {
        Self::Continuing
    }
}

