/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BookshelfAuthorResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "monitored", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub monitored: Option<Option<bool>>,
    #[serde(rename = "books", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub books: Option<Option<Vec<models::BookResource>>>,
}

impl BookshelfAuthorResource {
    pub fn new() -> BookshelfAuthorResource {
        BookshelfAuthorResource {
            id: None,
            monitored: None,
            books: None,
        }
    }
}

