/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BookshelfResource {
    #[serde(rename = "authors", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub authors: Option<Option<Vec<models::BookshelfAuthorResource>>>,
    #[serde(rename = "monitoringOptions", skip_serializing_if = "Option::is_none")]
    pub monitoring_options: Option<Box<models::MonitoringOptions>>,
    #[serde(rename = "monitorNewItems", skip_serializing_if = "Option::is_none")]
    pub monitor_new_items: Option<models::NewItemMonitorTypes>,
}

impl BookshelfResource {
    pub fn new() -> BookshelfResource {
        BookshelfResource {
            authors: None,
            monitoring_options: None,
            monitor_new_items: None,
        }
    }
}

