/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BookFileListResource {
    #[serde(rename = "bookFileIds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub book_file_ids: Option<Option<Vec<i32>>>,
    #[serde(rename = "quality", skip_serializing_if = "Option::is_none")]
    pub quality: Option<Box<models::QualityModel>>,
}

impl BookFileListResource {
    pub fn new() -> BookFileListResource {
        BookFileListResource {
            book_file_ids: None,
            quality: None,
        }
    }
}

