/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BookFileResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "authorId", skip_serializing_if = "Option::is_none")]
    pub author_id: Option<i32>,
    #[serde(rename = "bookId", skip_serializing_if = "Option::is_none")]
    pub book_id: Option<i32>,
    #[serde(rename = "path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub path: Option<Option<String>>,
    #[serde(rename = "size", skip_serializing_if = "Option::is_none")]
    pub size: Option<i64>,
    #[serde(rename = "dateAdded", skip_serializing_if = "Option::is_none")]
    pub date_added: Option<String>,
    #[serde(rename = "quality", skip_serializing_if = "Option::is_none")]
    pub quality: Option<Box<models::QualityModel>>,
    #[serde(rename = "qualityWeight", skip_serializing_if = "Option::is_none")]
    pub quality_weight: Option<i32>,
    #[serde(rename = "indexerFlags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub indexer_flags: Option<Option<i32>>,
    #[serde(rename = "mediaInfo", skip_serializing_if = "Option::is_none")]
    pub media_info: Option<Box<models::MediaInfoResource>>,
    #[serde(rename = "qualityCutoffNotMet", skip_serializing_if = "Option::is_none")]
    pub quality_cutoff_not_met: Option<bool>,
    #[serde(rename = "audioTags", skip_serializing_if = "Option::is_none")]
    pub audio_tags: Option<Box<models::ParsedTrackInfo>>,
}

impl BookFileResource {
    pub fn new() -> BookFileResource {
        BookFileResource {
            id: None,
            author_id: None,
            book_id: None,
            path: None,
            size: None,
            date_added: None,
            quality: None,
            quality_weight: None,
            indexer_flags: None,
            media_info: None,
            quality_cutoff_not_met: None,
            audio_tags: None,
        }
    }
}

