/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BookFileListLazyLoaded {
    #[serde(rename = "value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub value: Option<Option<Vec<models::BookFile>>>,
    #[serde(rename = "isLoaded", skip_serializing_if = "Option::is_none")]
    pub is_loaded: Option<bool>,
}

impl BookFileListLazyLoaded {
    pub fn new() -> BookFileListLazyLoaded {
        BookFileListLazyLoaded {
            value: None,
            is_loaded: None,
        }
    }
}

