/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BookEditorResource {
    #[serde(rename = "bookIds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub book_ids: Option<Option<Vec<i32>>>,
    #[serde(rename = "monitored", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub monitored: Option<Option<bool>>,
    #[serde(rename = "deleteFiles", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub delete_files: Option<Option<bool>>,
    #[serde(rename = "addImportListExclusion", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub add_import_list_exclusion: Option<Option<bool>>,
}

impl BookEditorResource {
    pub fn new() -> BookEditorResource {
        BookEditorResource {
            book_ids: None,
            monitored: None,
            delete_files: None,
            add_import_list_exclusion: None,
        }
    }
}

