/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BooksMonitoredResource {
    #[serde(rename = "bookIds", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub book_ids: Option<Option<Vec<i32>>>,
    #[serde(rename = "monitored", skip_serializing_if = "Option::is_none")]
    pub monitored: Option<bool>,
}

impl BooksMonitoredResource {
    pub fn new() -> BooksMonitoredResource {
        BooksMonitoredResource {
            book_ids: None,
            monitored: None,
        }
    }
}

