/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomFormat {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "includeCustomFormatWhenRenaming", skip_serializing_if = "Option::is_none")]
    pub include_custom_format_when_renaming: Option<bool>,
    #[serde(rename = "specifications", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub specifications: Option<Option<Vec<models::ICustomFormatSpecification>>>,
}

impl CustomFormat {
    pub fn new() -> CustomFormat {
        CustomFormat {
            id: None,
            name: None,
            include_custom_format_when_renaming: None,
            specifications: None,
        }
    }
}

