/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum FileDateType {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "bookReleaseDate")]
    BookReleaseDate,

}

impl std::fmt::Display for FileDateType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "none"),
            Self::BookReleaseDate => write!(f, "bookReleaseDate"),
        }
    }
}

impl Default for FileDateType {
    fn default() -> FileDateType {
        Self::None
    }
}

