/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ImportListType {
    #[serde(rename = "program")]
    Program,
    #[serde(rename = "goodreads")]
    Goodreads,
    #[serde(rename = "other")]
    Other,

}

impl std::fmt::Display for ImportListType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Program => write!(f, "program"),
            Self::Goodreads => write!(f, "goodreads"),
            Self::Other => write!(f, "other"),
        }
    }
}

impl Default for ImportListType {
    fn default() -> ImportListType {
        Self::Program
    }
}

