/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ImportListMonitorType {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "specificBook")]
    SpecificBook,
    #[serde(rename = "entireAuthor")]
    EntireAuthor,

}

impl std::fmt::Display for ImportListMonitorType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "none"),
            Self::SpecificBook => write!(f, "specificBook"),
            Self::EntireAuthor => write!(f, "entireAuthor"),
        }
    }
}

impl Default for ImportListMonitorType {
    fn default() -> ImportListMonitorType {
        Self::None
    }
}

