/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ManualImportUpdateResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub path: Option<Option<String>>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "authorId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub author_id: Option<Option<i32>>,
    #[serde(rename = "bookId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub book_id: Option<Option<i32>>,
    #[serde(rename = "foreignEditionId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub foreign_edition_id: Option<Option<String>>,
    #[serde(rename = "quality", skip_serializing_if = "Option::is_none")]
    pub quality: Option<Box<models::QualityModel>>,
    #[serde(rename = "releaseGroup", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub release_group: Option<Option<String>>,
    #[serde(rename = "indexerFlags", skip_serializing_if = "Option::is_none")]
    pub indexer_flags: Option<i32>,
    #[serde(rename = "downloadId", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub download_id: Option<Option<String>>,
    #[serde(rename = "additionalFile", skip_serializing_if = "Option::is_none")]
    pub additional_file: Option<bool>,
    #[serde(rename = "replaceExistingFiles", skip_serializing_if = "Option::is_none")]
    pub replace_existing_files: Option<bool>,
    #[serde(rename = "disableReleaseSwitching", skip_serializing_if = "Option::is_none")]
    pub disable_release_switching: Option<bool>,
    #[serde(rename = "rejections", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub rejections: Option<Option<Vec<models::Rejection>>>,
}

impl ManualImportUpdateResource {
    pub fn new() -> ManualImportUpdateResource {
        ManualImportUpdateResource {
            id: None,
            path: None,
            name: None,
            author_id: None,
            book_id: None,
            foreign_edition_id: None,
            quality: None,
            release_group: None,
            indexer_flags: None,
            download_id: None,
            additional_file: None,
            replace_existing_files: None,
            disable_release_switching: None,
            rejections: None,
        }
    }
}

