/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaCover {
    #[serde(rename = "url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub url: Option<Option<String>>,
    #[serde(rename = "coverType", skip_serializing_if = "Option::is_none")]
    pub cover_type: Option<models::MediaCoverTypes>,
    #[serde(rename = "extension", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub extension: Option<Option<String>>,
}

impl MediaCover {
    pub fn new() -> MediaCover {
        MediaCover {
            url: None,
            cover_type: None,
            extension: None,
        }
    }
}

