/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaManagementConfigResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "autoUnmonitorPreviouslyDownloadedBooks", skip_serializing_if = "Option::is_none")]
    pub auto_unmonitor_previously_downloaded_books: Option<bool>,
    #[serde(rename = "recycleBin", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub recycle_bin: Option<Option<String>>,
    #[serde(rename = "recycleBinCleanupDays", skip_serializing_if = "Option::is_none")]
    pub recycle_bin_cleanup_days: Option<i32>,
    #[serde(rename = "downloadPropersAndRepacks", skip_serializing_if = "Option::is_none")]
    pub download_propers_and_repacks: Option<models::ProperDownloadTypes>,
    #[serde(rename = "createEmptyAuthorFolders", skip_serializing_if = "Option::is_none")]
    pub create_empty_author_folders: Option<bool>,
    #[serde(rename = "deleteEmptyFolders", skip_serializing_if = "Option::is_none")]
    pub delete_empty_folders: Option<bool>,
    #[serde(rename = "fileDate", skip_serializing_if = "Option::is_none")]
    pub file_date: Option<models::FileDateType>,
    #[serde(rename = "watchLibraryForChanges", skip_serializing_if = "Option::is_none")]
    pub watch_library_for_changes: Option<bool>,
    #[serde(rename = "rescanAfterRefresh", skip_serializing_if = "Option::is_none")]
    pub rescan_after_refresh: Option<models::RescanAfterRefreshType>,
    #[serde(rename = "allowFingerprinting", skip_serializing_if = "Option::is_none")]
    pub allow_fingerprinting: Option<models::AllowFingerprinting>,
    #[serde(rename = "setPermissionsLinux", skip_serializing_if = "Option::is_none")]
    pub set_permissions_linux: Option<bool>,
    #[serde(rename = "chmodFolder", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub chmod_folder: Option<Option<String>>,
    #[serde(rename = "chownGroup", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub chown_group: Option<Option<String>>,
    #[serde(rename = "skipFreeSpaceCheckWhenImporting", skip_serializing_if = "Option::is_none")]
    pub skip_free_space_check_when_importing: Option<bool>,
    #[serde(rename = "minimumFreeSpaceWhenImporting", skip_serializing_if = "Option::is_none")]
    pub minimum_free_space_when_importing: Option<i32>,
    #[serde(rename = "copyUsingHardlinks", skip_serializing_if = "Option::is_none")]
    pub copy_using_hardlinks: Option<bool>,
    #[serde(rename = "importExtraFiles", skip_serializing_if = "Option::is_none")]
    pub import_extra_files: Option<bool>,
    #[serde(rename = "extraFileExtensions", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub extra_file_extensions: Option<Option<String>>,
}

impl MediaManagementConfigResource {
    pub fn new() -> MediaManagementConfigResource {
        MediaManagementConfigResource {
            id: None,
            auto_unmonitor_previously_downloaded_books: None,
            recycle_bin: None,
            recycle_bin_cleanup_days: None,
            download_propers_and_repacks: None,
            create_empty_author_folders: None,
            delete_empty_folders: None,
            file_date: None,
            watch_library_for_changes: None,
            rescan_after_refresh: None,
            allow_fingerprinting: None,
            set_permissions_linux: None,
            chmod_folder: None,
            chown_group: None,
            skip_free_space_check_when_importing: None,
            minimum_free_space_when_importing: None,
            copy_using_hardlinks: None,
            import_extra_files: None,
            extra_file_extensions: None,
        }
    }
}

