/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MetadataProfileResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub name: Option<Option<String>>,
    #[serde(rename = "minPopularity", skip_serializing_if = "Option::is_none")]
    pub min_popularity: Option<f64>,
    #[serde(rename = "skipMissingDate", skip_serializing_if = "Option::is_none")]
    pub skip_missing_date: Option<bool>,
    #[serde(rename = "skipMissingIsbn", skip_serializing_if = "Option::is_none")]
    pub skip_missing_isbn: Option<bool>,
    #[serde(rename = "skipPartsAndSets", skip_serializing_if = "Option::is_none")]
    pub skip_parts_and_sets: Option<bool>,
    #[serde(rename = "skipSeriesSecondary", skip_serializing_if = "Option::is_none")]
    pub skip_series_secondary: Option<bool>,
    #[serde(rename = "allowedLanguages", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allowed_languages: Option<Option<String>>,
    #[serde(rename = "minPages", skip_serializing_if = "Option::is_none")]
    pub min_pages: Option<i32>,
    #[serde(rename = "ignored", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ignored: Option<Option<Vec<String>>>,
}

impl MetadataProfileResource {
    pub fn new() -> MetadataProfileResource {
        MetadataProfileResource {
            id: None,
            name: None,
            min_popularity: None,
            skip_missing_date: None,
            skip_missing_isbn: None,
            skip_parts_and_sets: None,
            skip_series_secondary: None,
            allowed_languages: None,
            min_pages: None,
            ignored: None,
        }
    }
}

