/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RenameBookResource {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "authorId", skip_serializing_if = "Option::is_none")]
    pub author_id: Option<i32>,
    #[serde(rename = "bookId", skip_serializing_if = "Option::is_none")]
    pub book_id: Option<i32>,
    #[serde(rename = "bookFileId", skip_serializing_if = "Option::is_none")]
    pub book_file_id: Option<i32>,
    #[serde(rename = "existingPath", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub existing_path: Option<Option<String>>,
    #[serde(rename = "newPath", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub new_path: Option<Option<String>>,
}

impl RenameBookResource {
    pub fn new() -> RenameBookResource {
        RenameBookResource {
            id: None,
            author_id: None,
            book_id: None,
            book_file_id: None,
            existing_path: None,
            new_path: None,
        }
    }
}

