/*
 * Readarr
 *
 * Readarr API docs
 *
 * The version of the OpenAPI document: v0.4.10.2734
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SeriesBookLink {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "position", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub position: Option<Option<String>>,
    #[serde(rename = "seriesPosition", skip_serializing_if = "Option::is_none")]
    pub series_position: Option<i32>,
    #[serde(rename = "seriesId", skip_serializing_if = "Option::is_none")]
    pub series_id: Option<i32>,
    #[serde(rename = "bookId", skip_serializing_if = "Option::is_none")]
    pub book_id: Option<i32>,
    #[serde(rename = "isPrimary", skip_serializing_if = "Option::is_none")]
    pub is_primary: Option<bool>,
    #[serde(rename = "series", skip_serializing_if = "Option::is_none")]
    pub series: Option<Box<models::SeriesLazyLoaded>>,
    #[serde(rename = "book", skip_serializing_if = "Option::is_none")]
    pub book: Option<Box<models::BookLazyLoaded>>,
}

impl SeriesBookLink {
    pub fn new() -> SeriesBookLink {
        SeriesBookLink {
            id: None,
            position: None,
            series_position: None,
            series_id: None,
            book_id: None,
            is_primary: None,
            series: None,
            book: None,
        }
    }
}

